// Code generated by MockGen. DO NOT EDIT.
// Source: aws.go
//
// Generated by this command:
//
//	mockgen -source=aws.go -destination=aws_mock.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAWSTokenGenerator is a mock of AWSTokenGenerator interface.
type MockAWSTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockAWSTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockAWSTokenGeneratorMockRecorder is the mock recorder for MockAWSTokenGenerator.
type MockAWSTokenGeneratorMockRecorder struct {
	mock *MockAWSTokenGenerator
}

// NewMockAWSTokenGenerator creates a new mock instance.
func NewMockAWSTokenGenerator(ctrl *gomock.Controller) *MockAWSTokenGenerator {
	mock := &MockAWSTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockAWSTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSTokenGenerator) EXPECT() *MockAWSTokenGeneratorMockRecorder {
	return m.recorder
}

// GenerateAuthToken mocks base method.
func (m *MockAWSTokenGenerator) GenerateAuthToken(ctx context.Context, region string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthToken", ctx, region)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAuthToken indicates an expected call of GenerateAuthToken.
func (mr *MockAWSTokenGeneratorMockRecorder) GenerateAuthToken(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthToken", reflect.TypeOf((*MockAWSTokenGenerator)(nil).GenerateAuthToken), ctx, region)
}
