---
name: build
on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
    - main
    - release/**
jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: github
      url: ${{ steps.tag.outputs.version }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 50
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Tag
        id: tag
        uses: martoc/action-tag@v0
      - name: Init build
        run: |
          export BIN_NAME=$(basename `pwd`)
          echo "BIN_NAME=$BIN_NAME" >> "$GITHUB_ENV"
          make init
      - name: Build
        run: make build
      - name: Run Integration Tests
        run: make run-integration-tests
      - name: Build Container
        uses: martoc/action-container-build@v0
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release on GitHub
        uses: martoc/action-release@v0
